### PR TITLE
CVE_ENVIRONMENT can be `test` but not `dev`

### PR DESCRIPTION
**Pull request by zmanion**
```
$ CVE_ENVIRONMENT=test cve org users
USERNAME           NAME         ROLES   ACTIVE   CREATED                    MODIFIED
amanion@cert.org   Art Manion   ADMIN   Yes      Wed Feb  2 21:18:04 2022   Wed Feb  2 21:18:04 2022

$ CVE_ENVIRONMENT=dev cve org users
ERROR: 401 Client Error: Unauthorized for url: https://cveawg-dev.mitre.org/api/org/certcc/users
DETAILS: {'error': 'UNAUTHORIZED', 'message': 'Unauthorized'}
```

### CODE REVIEW

**Comment by mprpic** [comment]
All three of these envs exists but they seem to require different sets of credentials (which is why you might be getting a 403):

```
    ENVS = {
        "prod": "https://cveawg.mitre.org/api/",
        "dev": "https://cveawg-dev.mitre.org/api/",
        "test": "https://cveawg-test.mitre.org/api/",
    }
```

MITRE hasn't really made any guarantees for the dev and test envs so they tend to come and go. Perhaps it would be best to just remove them from cvelib and expect users to always define non-prod envs via `CVE_API_URL`. Wdyt?

**Comment by zmanion** [comment]
Don't have a strong opinion, I'd suggest either document that all three envs are possible, may require different creds, and that dev and test do not have guarantees, or drop CVE_ENVIRONMENT and just use CVE_API_URL. Seems like CVE_ENVIRONMENT is only affects the URL so removing CVE_ENVIRONMENT is safe.

**Comment by zmanion** [comment]
I provided a documentation change if you go that route.

**Review by mprpic — APPROVED** [review]
Looks good!

**Pull request merged**
